apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rt5kr5mv2-nodejs 
  janus-idp.io/tekton: rt5kr5mv2-nodejs
  backstage.io/kubernetes-id: rt5kr5mv2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rt5kr5mv2-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml