apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rt5kr5mv2-nodejs
  janus-idp.io/tekton: rt5kr5mv2-nodejs
  backstage.io/kubernetes-id: rt5kr5mv2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rt5kr5mv2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
